name: Bug report
description: Report bugs with the port here
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your bug here."
    validations:
      required: true

  - type: textarea
    id: terminal
    attributes:
      label: "Crash Log or logcat logs (if existing)"
      render: bash
    validations:
      required: false

  - type: dropdown
    id: modding
    attributes:
      label: "Are you modding a build from source or with Lua?"
      options:
        - Lua
        - Source
        - Lua and Source
        - I am not modding
    validations:
      required: true

  - type: dropdown
    id: btarget
    attributes:
      label: "What is your build target?"
      options:
        - "Desktop (Linux, Windows or Mac)"
        - "Emscripten"
        - "Android"
        - "iOS"
        - "HashLink"
        - "Flash/AIR"
        - "Unknown/I don't know"
    validations:
      required: true

  - type: input
    id: buildsummary
    attributes:
      label: "Did you edit anything in this build? If so, mention or summarize your changes."
      placeholder: "Yes, I edited ClientPrefs.hx and tried to add a new setting"
    validations:
      required: true
